# Configuration for the labeler action
# Add labels to pull requests based on the files that are modified

# Label for frontend changes
frontend:
  - "app/**/*"
  - "components/**/*"
  - "styles/**/*"
  - "public/**/*"
  - "*.tsx"
  - "*.ts"
  - "*.css"

# Label for backend/functions changes
backend:
  - "functions/**/*"
  - "firebase/**/*"
  - "scripts/**/*"

# Label for configuration changes
config:
  - "*.json"
  - "*.js"
  - "*.mjs"
  - "*.config.*"
  - ".github/**/*"

# Label for documentation changes
documentation:
  - "*.md"
  - "docs/**/*"

# Label for dependency changes
dependencies:
  - "package*.json"
  - "pnpm-lock.yaml"
  - "yarn.lock"

ci/cd:
  - ".github/workflows/**/*"
  - ".github/labeler.yml"
  - ".github/issue_template.md"
  - ".github/**/*.yml"
