# Configuration for the labeler action
# Add labels to pull requests based on the files that are modified

# Label for frontend changes
frontend:
- changed-files:
  - any-glob-to-any-file:
    - 'app/**/*'
    - 'components/**/*'
    - 'styles/**/*'
    - 'public/**/*'
    - '**/*.tsx'
    - '**/*.ts'
    - '**/*.css'
    - 'hooks/**/*'

# Label for backend/functions changes
backend:
- changed-files:
  - any-glob-to-any-file:
    - 'functions/**/*'
    - 'firebase/**/*'
    - 'scripts/**/*'
    - 'utils/**/*'
    - 'types/**/*'

# Label for configuration changes
config:
- changed-files:
  - any-glob-to-any-file:
    - '*.json'
    - '*.js'
    - '*.mjs'
    - '*.config.*'
    - '.github/**/*'
    - 'tailwind.config.ts'
    - 'tsconfig.json'
    - 'next.config.mjs'
    - 'postcss.config.mjs'
    - 'components.json'

# Label for documentation changes
documentation:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'
    - 'docs/**/*'

# Label for dependency changes
dependencies:
- changed-files:
  - any-glob-to-any-file:
    - 'package*.json'
    - 'pnpm-lock.yaml'
    - 'yarn.lock'

# Label for CI/CD changes
ci-cd:
- changed-files:
  - any-glob-to-any-file:
    - '.github/workflows/**/*'
    - '.github/**/*.yml'
    - '.github/**/*.yaml'

# Label for Firebase/Database changes
database:
- changed-files:
  - any-glob-to-any-file:
    - 'firestore.*'
    - 'firebase.json'
    - 'storage.rules'

# Label for UI components
ui:
- changed-files:
  - any-glob-to-any-file:
    - 'components/ui/**/*'

# Label for authentication related changes
auth:
- changed-files:
  - any-glob-to-any-file:
    - 'app/auth/**/*'
    - 'app/context/AuthContext.tsx'
    - 'functions/auth.js'

# Label for admin related changes
admin:
- changed-files:
  - any-glob-to-any-file:
    - 'app/admin/**/*'
    - 'app/context/AdminContext.tsx'
    - 'scripts/*admin*'

# Label for cart/checkout functionality
ecommerce:
- changed-files:
  - any-glob-to-any-file:
    - 'app/cart/**/*'
    - 'app/checkout/**/*'
    - 'app/context/CartContext.tsx'
    - 'app/menu/**/*'
