frontend:
  - 'app/**'
  - 'components/**'
  - 'styles/**'
  - 'public/**'
  - '**/*.tsx'
  - '**/*.ts'
  - '**/*.css'

backend:
  - 'functions/**'
  - 'firebase/**'
  - 'scripts/**'

config:
  - '**/*.json'
  - '**/*.js'
  - '**/*.mjs'
  - '**/*.config.*'
  - '.github/*.yml'
  - '.github/*.yaml'

documentation:
  - '**/*.md'
  - 'docs/**'

dependencies:
  - 'package*.json'
  - 'pnpm-lock.yaml'
  - 'yarn.lock'

ci-cd:
  - '.github/workflows/**'
